DECLARE @CustomerID INT
DECLARE @FIRSTNAME NVARCHAR(50)
DECLARE @MIDDLENAME NVARCHAR(50)
DECLARE @LASTNATME NVARCHAR(50)
DECLARE @PHONENUMBER NVARCHAR(25)

SELECT Sales.Customer.CustomerID,
Person.Person.FirstName,
Person.Person.MiddleName,
Person.Person.LastName,
Person.PersonPhone.PhoneNumber
FROM ((Sales.Customer INNER JOIN Person.Person
ON Sales.Customer.PersonID - Person.Person.BusinessEntityID)
INNER JOIN Person.PersonPhone
ON Person.Person.BusinessEntityID = Person.PersonPhone.BusinessEntityID)

OPEN CUSTOMER_CURSOR
FETCH NEXT FROM CUSTOMER_CURSOR INTO @CUSTOMERID,@FIRSTNAME,
@MIDDLENAME,@LASTNAME, @PHONENUMBER
WHILE (@@FETCH_STATUS = 0)
BEGIN
	PRINT CAST(@CUSTOMERID AS NVARCHAR(50))+ ' ' +
	@FIRSTNAME + ' ' + 
	CASE WHEN @MIDDLENAME IS NULL THEN '*' ELSE @MIDDLENAME END + ' ' +
	@LASTNAME
	FETCH NEXT FROM CUSTOMER_CURSOR INTO @CUSTOMERID,@FIRSTNAME,
	@MIDDLENAME,@LASTNAME,@PHONENUMBER
END
CLOSE CUSTOMER_CURSOR
DEALLOCATE CUSTOMER_CURSOR
