USE AdventureWorks2008R2
GO

DECLARE @BUSINESSENTITYID INT
DECLARE @Title NVARCHAR (50)
DECLARE @FirstName NVARCHAR (25)
DECLARE @MiddleName NVARCHAR (5)
DECLARE @LastName NVARCHAR (25)

DECLARE CURSOR_PERSON CURSOR FOR
SELECT BusinessEntityID,Title,FirstName, MiddleName, LastName FROM Person.Person

OPEN CURSOR_PERSON
FETCH NEXT FROM CURSOR_PERSON INTO @BUSINESSENTITYID, @Title, @FirstName, @MiddleName, @LastName

WHILE (@@FETCH_STATUS = 0)
BEGIN
	INSERT INTO PERSONTOEXPORT (BUSINESSENTITYID,Title,FirstName, MiddleName, LastName) VALUES (@BUSINESSENTITYID,@Title,@FirstName,@MiddleName,@LastName)
	FETCH  NEXT FROM CURSOR_PERSON INTO
@BUSINESSENTITYID, @Title, @FirstName, @MiddleName, @LastName
END
CLOSE CURSOR_PERSON
DEALLOCATE CURSOR_PERSON
------------------------------
SELECT * FROM PERSONTOEXPORT
SELECT * FROM AdventureWorks2008R2.Person.Person

CREATE TABLE PERSONTOEXPORT
(
	BUSINESSENTITYID INT PRIMARY KEY NOT NULL,
	Title NVARCHAR (50)  NOT NULL,
	FirstName NVARCHAR (25) NOT NULL,
	MiddleName NVARCHAR (5) NOT NULL,
	LastName NVARCHAR (25) NOT NULL,
)