CREATE TABLE CLIENTES
(
	CODIGO INT NOT NULL,
	NOMBRE NVARCHAR (25)  NOT NULL,
	DESCRIPCION NVARCHAR (25) NOT NULL,
	CREDITMAX SMALLMONEY NOT NULL,
	OPERATIVO BIT NOT NULL,
	POSICION NUMERIC NOT NULL,
	CATEGORIA INT NOT NULL
)
DROP TABLE CLIENTES
--------------------------
SELECT *FROM CLIENTES

INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('001','Joan','Alumno ASIX','300','0','1','10')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('002','Marc','Alumno ASIX','200','1','2','10')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('003','Xisco','Alumno ASIX','500','1','3','10')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('004','Pepe','Alumno ASIX','3000','1','4','10')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('005','Antonio','Alumno ASIX','6300','1','5','20')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('006','Jesus','Alumno ASIX','45300','0','6','20')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('007','Luis','Alumno ASIX','800','0','7','20')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('008','Daniel','Alumno ASIX','600','0','8','20')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('009','Tomas','Alumno ASIX','500','1','9','30')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('010','Miquel','Alumno ASIX','350','0','10','30')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('011','Carlos','Alumno ASIX','36','1','11','30')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('012','Enric','Alumno ASIX','60','0','12','30')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('013','Angel','Alumno ASIX','185','1','13','30')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('014','Jorge','Alumno ASIX','520','0','14','40')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('015','Hugo','Alumno ASIX','14790','1','15','40')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('016','Alberto','Alumno ASIX','6450','0','16','40')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('017','Alejandro','Alumno ASIX','370','1','17','40')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('018','Tomeu','Alumno ASIX','9460','1','18','40')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('019','Nicolas','Alumno ASIX','15000','1','19','50')
INSERT INTO CLIENTES (CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES ('020','Adrian','Alumno ASIX','100450','0','20','50')

-------------------------

DECLARE @CODIGO INT
DECLARE @NOMBRE NVARCHAR (25)
DECLARE @DESCRIPCION NVARCHAR (25)
DECLARE @CREDITMAX SMALLMONEY
DECLARE @OPERATIVO BIT
DECLARE @POSICION NUMERIC
DECLARE @CATEGORIA INT 

DECLARE CURSOR_CLIENTES SCROLL CURSOR FOR
SELECT CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA FROM CLIENTES

OPEN CURSOR_CLIENTES
FETCH NEXT FROM CURSOR_CLIENTES INTO @CODIGO, @NOMBRE, @DESCRIPCION, @CREDITMAX, @OPERATIVO, @POSICION, @CATEGORIA

WHILE (@@FETCH_STATUS = 0)
BEGIN
	INSERT INTO CLIENTES(CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA) VALUES (@CODIGO, @NOMBRE, @DESCRIPCION, @CREDITMAX, @OPERATIVO, '0', @CATEGORIA)
	FETCH RELATIVE 1 FROM CURSOR_CLIENTES INTO @CODIGO, @NOMBRE, @DESCRIPCION, @CREDITMAX, @OPERATIVO, @POSICION, @CATEGORIA
END
CLOSE CURSOR_CLIENTES
DEALLOCATE CURSOR_CLIENTES
--------------------------------
DECLARE @CODIGO INT
DECLARE @NOMBRE NVARCHAR (25)
DECLARE @DESCRIPCION NVARCHAR (25)
DECLARE @CREDITMAX SMALLMONEY
DECLARE @OPERATIVO BIT
DECLARE @POSICION NUMERIC
DECLARE @CATEGORIA INT 

DECLARE CURSOR_CLIENTESUPDATE SCROLL CURSOR FOR
SELECT CODIGO, NOMBRE, DESCRIPCION, CREDITMAX, OPERATIVO,POSICION, CATEGORIA FROM CLIENTES WHERE POSICION <> 0

OPEN CURSOR_CLIENTESUPDATE
FETCH NEXT FROM CURSOR_CLIENTESUPDATE INTO @NOMBRE, @DESCRIPCION, @POSICION, @CATEGORIA

WHILE (@@FETCH_STATUS = 0)
IF(SELECT NOMBRE, DESCRIPCION, CATEGORIA FROM CLIENTES WHERE NOMBRE = @NOMBRE AND DESCRIPCION = @DESCRIPCION AND CATEGORIA = @CATEGORIA)
BEGIN
	UPDATE CLIENTES SET POSICION = @POSICION WHERE NOMBRE = @NOMBRE AND DESCRIPCION = @DESCRIPCION AND CATEGORIA = @CATEGORIA AND POSICION = 0
	FETCH RELATIVE 1 FROM CURSOR_CLIENTESUPDATE INTO @NOMBRE, @DESCRIPCION, @POSICION, @CATEGORIA
END
CLOSE CURSOR_CLIENTESUPDATE
DEALLOCATE CURSOR_CLIENTESUPDATE

