@ ECHO OFF

CLS
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO         ###############################################
ECHO         #                                             #
ECHO         #   GESTIONAR ETIQUETA                        #
ECHO         #                                             #
ECHO         #                                             #
ECHO         #    21. ETIQUETAR UNIDAD                     #
ECHO         #    22. BORRAR EQUIQUETA                     #
ECHO         #    23. CONSULTAR ETIQUETA                   #
ECHO         #    24. VOLVER                               #
ECHO         #                                             #
ECHO         ###############################################
ECHO.
ECHO.
ECHO.
PROMPT OPCION? 
