@ ECHO OFF

CLS
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO         ###############################################
ECHO         #                                             #
ECHO         #   MENU PRINCIPAL                            #
ECHO         #                                             #
ECHO         #                                             #
ECHO         #    1. MOSTRAR ARBOL                         #
ECHO         #    2. GESTIONAR ETIQUETA                    #
ECHO         #    3. CHEQUEAR UNIDAD                       #
ECHO         #    4. SALIR AL DOS                          #
ECHO         #                                             #
ECHO         ###############################################
ECHO.
ECHO.
ECHO.
PROMPT OPCION? 
